### ISSUE TITLE
repository size too large

### ISSUE THREAD

**Issue by bmulas1535** [Lambda-School-Labs/tagger-ds#57]
Need to clean - recommend using BFG to remove source / binary blobs from commit history.

**Comment by bmulas1535** [comment]
Used BFG to clean git history for blob removal. Size decreased from 312MiB -> ~80MiB. 
Need to push this revised history to master.

**Comment by filchyboy** [comment]
Could you explain this? I just tried to update and it pulled down over 300mb. Now I have a branch that needs resolved.

**Comment by bmulas1535** [comment]
The repo history included every large file ever uploaded to the repository, causing it's size to exceed reasonable. I've removed all of the bloat from history, reducing the repository size down to less than 1MB.
