### ISSUE TITLE
Code-base not optimized.

### ISSUE THREAD

**Issue by bmulas1535** [Lambda-School-Labs/tagger-ds#80]
**Short description of issue:**
The code base is poorly optimized. Many functions contain too many steps or introduce exceeding amounts of overhead.

**Suggestions:**
1. Break down long functions into more concise parts that commit to doing a specific task.
2. Remove variable pointers to redundant steps
3. Streamline processes for performance.

**Comment by bmulas1535** [comment]
Issue being developed in [branch 80-optimize-codebase](https://github.com/Lambda-School-Labs/tagger-ds/tree/80-optimize-codebase)

**Comment by filchyboy** [comment]
This has been rectified?
